{% set name = "sparkmagic" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-incubator/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d2c602744b43bd5c07a8e99129444e38413d065d5621c1fdd518af64dd05a880
build:
  number: 0
  skip: True  # [py<36 or ppc64le]
  script: cd sparkmagic && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - autovizwidget >=0.6
    - hdijupyterutils >=0.6
    - ipykernel >=4.2.2
    - ipython >=4.0.2
    - ipywidgets >5.0.0
    - nest-asyncio 1.5.5
    - notebook >=4.2
    - numpy
    - pandas >=0.17.1
    - requests
    - requests-kerberos >=0.8.0
    - tornado >=4

test:
  imports:
    - sparkmagic
  source_files:
    - sparkmagic/sparkmagic/tests
  requires:
    - nose
    - mock
    - pip
    - qtconsole  # [linux and (aarch64 or ppc64le)]
  commands:
    - pip check
    - nosetests sparkmagic/sparkmagic/tests

about:
  home: https://github.com/jupyter-incubator/sparkmagic
  license: BSD-3-Clause
  license_family: BSD
  summary: Jupyter magics and kernels for working with remote Spark clusters
  license_file: LICENSE.md
  doc_url: https://github.com/jupyter-incubator/sparkmagic#readme
  dev_url: https://github.com/jupyter-incubator/sparkmagic/tree/master/sparkmagic

extra:
  recipe-maintainers:
    - danielfrg
    - itamarst
    - dbast
