{% set name = "sparkmagic" %}
{% set version = "0.12.6" %}
{% set hash_type = "sha256" %}
{% set hash_val = "044bc04e683438d68cfc90ff2f6180a243dc4f9dd2477b0ea9405cc65bb40c1b" %}

package:
    name: {{ name }}
    version: 1!{{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    {{ hash_type }}: {{ hash_val }}
    patches:
        0001-Remove-PySpark3-kernel.patch

build:
    number: 0
    skip: true  # [win]
    script: python setup.py install

requirements:
    host:
        - python
    run:
        - python
        - notebook >=4.2
        - ipykernel >=4.2.2
        - ipywidgets >=5.0.0
        - ipython
        - widgetsnbextension
        - hdijupyterutils
        - autovizwidget
        - numpy
        - pandas
        - requests
        - requests-kerberos

test:
    imports:
        - sparkmagic

about:
    home: https://github.com/jupyter-incubator/sparkmagic
    license: BSD 3-clause
    summary: Jupyter magics and kernels for working with remote Spark clusters

extra:
  recipe-maintainers:
    - danielfrg
