package:
    name: sparkmagic
    version: 0.12.7

source:
    git_url: https://github.com/jupyter-incubator/sparkmagic.git
    git_rev: 437ee02c359de5e85846eeae79f99977f198fa3b  # 0.12.7
    patches:
        0001-Remove-PySpark3-kernel.patch

build:
    number: 1002
    skip: true  # [win]
    script: cd sparkmagic && python setup.py install

requirements:
    host:
        - python
    run:
        - python
        - notebook >=4.2
        - ipykernel==4.9.0
        - ipywidgets >=5.0.0
        - ipython
        - widgetsnbextension
        - hdijupyterutils
        - autovizwidget
        - numpy
        - pandas
        - requests
        - requests-kerberos

test:
    source_files:
        - sparkmagic/sparkmagic/tests
    requires:
        - nose
        - mock
        - tornado
    imports:
        - sparkmagic
    commands:
        - nosetests sparkmagic/sparkmagic/tests

about:
    home: https://github.com/jupyter-incubator/sparkmagic
    license: BSD 3-clause
    summary: Jupyter magics and kernels for working with remote Spark clusters

extra:
  recipe-maintainers:
    - danielfrg
