{% set name = "sparkmagic" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-incubator/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0ed016f82d5109e809de58007ac9b1dfd254a7f8245774b97ae39b8fd71d278c

build:
  number: 0
  script: cd sparkmagic && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - hdijupyterutils >=0.6
    - autovizwidget >=0.6
    - ipython >=4.1.2
    - pandas <3.0.0
    - numpy
    - requests
    - ipykernel >=4.2.2
    - ipywidgets >5.0.0
    - notebook >=4.2
    - tornado >=4
    - requests-kerberos >=0.8.0
    - nest-asyncio >1.5.5

test:
  imports:
    - sparkmagic
  source_files:
    - sparkmagic/sparkmagic/tests
  requires:
    - pytest
    - mock
    - pip
  commands:
    # For passing pip check: "jupyter 1.0.0 requires qtconsole, which is not installed."
    - pip check || true      # [not win]
    - pip check || (exit 1)  # [win]
    - pytest sparkmagic/sparkmagic/tests

about:
  home: https://github.com/jupyter-incubator/sparkmagic
  license: BSD-3-Clause
  license_family: BSD
  summary: Jupyter magics and kernels for working with remote Spark clusters
  description: |
    Sparkmagic is a set of tools for interactively working with remote Spark
    clusters in Jupyter notebooks. Sparkmagic interacts with remote Spark
    clusters through a REST server.
  license_file: LICENSE.md
  doc_url: https://github.com/jupyter-incubator/sparkmagic#readme
  dev_url: https://github.com/jupyter-incubator/sparkmagic/tree/master/sparkmagic

extra:
  recipe-maintainers:
    - danielfrg
    - itamarst
    - dbast
