appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZEej1vYHVkT6YIo7wnSmE5pHlgnIG9NNZtMSzPXOLwUKPypBvUHpl/i68mp7li4DIgYOTVsdCTKp3rqJaioPNQ4MHg4OK6VUBerQ2ilXMrgXcIuF3IEytt4DfbS/pIKXKPoCKcywpWkRZCPnjxVcVhVsmzEDojEggjT/gsZw5jayOFBfIFGNimqWuRVE3xaMTc7VOFsx2IqyxTjUP0Mous7gEKESP74ATpoq8atQiv2ZEBOYPwgjnxPyetjMDCidmhN4eLbyKIzeUU7hUp62RntKTa80jAmAO/5da2rrY+tIgaI8OlUtzYU/qoEF6JlQ/d/o9rK39RTI6IAy5YbK17K6Cn1vBr84REr758y44VcPEE5O3ILo2/4Ry8OuRnhBrD5lmLohqruqCJeHJTYLKEHkVudEAQaoM5nJ17s59usoV9wa7nYodba7/x5dXJEJO9P+mP0H56+SXWECKevAirMbsELdqrHEemfEkzIypQyCaw/UlH+XictjL2l5zezuEW82/OVlZDWCVgYSQBOeVud3pHk5dzggatMOB2cQe3b3foW3GoFV2WSfEafz4dsnup+AImL39wEy06LP3YDRrnM36xE5fV6/nll6eFF5tmP3ebogxfbO8gGmRrQ38V1V6C/OsqA6LjSiIJNHNGea5ya2xoW0Xp4uQRmfhokAQvw=}
