travis:
  secure:
    BINSTAR_TOKEN: oZU5Vmfkf95RDgpj4PeVcutxbUKIqqFZY2POTPv/wOjLr+84idCcao8piJz91W/E3qMVrEgFXoZSTiDN6DhOJTnxdIPoDh/Hmmtk9JW3GL1GQ1GjuVWArDAdB+b0nzVuTaEGjimmFfPQapC/gC18CxrDrChtETbCtTNI0PzvIWNm0uhFbzLPFjef8COhxm1TCv6NYgDJ40JWP+Up8zoir557EVqHX8Afw6BLnKoQL64JA7047AzPFSOZiVy5iBAPk+NXAbAiN3EmOmbNPOwkJgHGchqezOsh5cbviQFxzNpt6AzEJlQk7uBJ2rp78eod8v0+N0ImwdzqHN77cG6jIkX2gT31vWN1zrAedof1L61VcFrwNLHCrrvYkFk3jygF6S9/GwlEvU2VXLBHpsn6p2Hn2OZWp86O0KMC3A4ZolSODykKINAH2Ml1ADmersRJxiFsz6ebwYNHaKdUdPuT++xEYB3pl/INkwGfUvf+EmA8AJdsq6mYBtgHz5XFHr0xEnrCz8idAoQVlYd3tevTOzcf2vH3i1MpXSeMmGbUCEEgec2+V8eF4kPWMI+yeoVd76irNkTz7YFw/unMbGA5Oh0FVkes0aMbc/ELlXCd74Ye9C1IyQrBIOyxiPmxnHxe65lOV8I8ELOaaREFNxm8o3kmn0VLKgRp7A4LWA0J83w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
